### ISSUE TITLE
Panic when using get_header on an ICMP packet.

### ISSUE THREAD

**Issue by hnorkowski** [ravi861/packet-rs#1]
I created a nftable rule to queue pings to 93.184.216.255. The scapy `packet.command()` looks like this:

```
IP(version=4, ihl=5, tos=0, len=84, id=46192, flags=2, frag=0, ttl=64, proto=1, chksum=15704, src='192.168.81.128', dst='93.184.216.255')/ICMP(type=8, code=0, chksum=47858, id=48377, seq=65, unused=b'')/Raw(load=b'\xc3!\xb5d\x00\x00\x00\x00Gy\x01\x00\x00\x00\x00\x00\x10\x11\x12\x13\x14\x15\x16\x17\x18\x19\x1a\x1b\x1c\x1d\x1e\x1f !"#$%&\'()*+,-./01234567')
```

To capture the packet in rust I use the [nfq crate](https://docs.rs/nfq/0.2.5/nfq/index.html).
packet-rs shows the following for `packet.show()`:

```
#### Ether            Size   Data
-------------------------------------------
dst                 :   48 : 45 00 00 54 83 dd
src                 :   48 : 40 00 40 01 6d eb
etype               :   16 : c0 a8

#### raw 84 bytes ####
45 00 00 54 83 dd 40 00 40 01 6d eb c0 a8 51 80
5d b8 d8 ff 08 00 8e 45 b8 0d 05 1f 73 21 b5 64
00 00 00 00 c5 34 00 00 00 00 00 00 10 11 12 13
14 15 16 17 18 19 1a 1b 1c 1d 1e 1f 20 21 22 23
24 25 26 27 28 29 2a 2b 2c 2d 2e 2f 30 31 32 33
34 35 36 37
```

It does not seem to parse the contained IPv4 and ICMP headers. Not sure why but thats not the bug I want to report here.
When I try to get any header from that header other than `Ether` the library panics: 
```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/hendrik/.cargo/registry/src/index.crates.io-6f17d22bba15001f/packet_rs-0.4.0/src/packet.rs:204:36
stack backtrace:
   0: rust_begin_unwind
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:578:5
   1: core::panicking::panic_fmt
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panicking.rs:67:14
   2: core::panicking::panic
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panicking.rs:117:5
   3: core::option::Option<T>::unwrap
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/option.rs:950:21
   4: packet_rs::packet::<impl core::ops::index::Index<&str> for packet_rs::Packet>::index
             at /home/hendrik/.cargo/registry/src/index.crates.io-6f17d22bba15001f/packet_rs-0.4.0/src/packet.rs:65:9
   5: packet_rs::packet::<impl packet_rs::Packet>::get_header
             at /home/hendrik/.cargo/registry/src/index.crates.io-6f17d22bba15001f/packet_rs-0.4.0/src/packet.rs:204:36
   6: rust_testing::main
             at ./src/main.rs:20:22
   7: core::ops::function::FnOnce::call_once
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
This is unexpected as the `get_header` function returns a Result. I would expect the library to return `Err(...)`

This is my code:
```rs
#![allow(dead_code)]

use nfq::{Queue, Verdict};
use packet_rs::headers::*;
use packet_rs::parser;
use packet_rs::Packet;

fn main() -> std::io::Result<()> {
    let mut queue = Queue::open()?;
    queue.bind(2)?;

    loop {
        let mut msg = queue.recv()?;

        let payload = msg.get_payload();
        let packet = parser::slow::parse(payload);

        packet.show();

        let header = packet.get_header::<IPv4>("IPv4");

        msg.set_verdict(Verdict::Accept);
        queue.verdict(msg)?;
    }
}
```
And this is the nft ruleset:
```
table inet my-table {
        chain com-example-chain {
                type filter hook output priority filter; policy accept;
                ip daddr 93.184.216.255 counter packets 1792 bytes 150528 queue to 2
        }
}
```

**Comment by Payn** [comment]
Having the same issue. I'm capturing all packets with pcap crate and first ICMP packet causes panic.

`let header = pkt.get_header("TCP");`


```
#### Ether            Size   Data
-------------------------------------------
dst                 :   48 : 7c 21 0e b0 0a 3f 
src                 :   48 : fa 16 b6 a1 b2 98 
etype               :   16 : 08 00 
#### IPv4             Size   Data
-------------------------------------------
version             :    4 : 04
ihl                 :    4 : 05
diffserv            :    8 : c0
total_len           :   16 : 00 58 
identification      :   16 : 75 d2 
flags               :    3 : 00
frag_startset       :   13 : 00 00
ttl                 :    8 : 40
protocol            :    8 : 01
header_checksum     :   16 : e9 89 
src                 :   32 : c2 1f bf b5 
dst                 :   32 : 8d 62 0b 52 
#### ICMP             Size   Data
-------------------------------------------
icmp_type           :    8 : 03
icmp_code           :    8 : 03
chksum              :   16 : 17 b5 

#### raw 102 bytes ####
7c 21 0e b0 0a 3f fa 16 b6 a1 b2 98 08 00 45 c0 
00 58 75 d2 00 00 40 01 e9 89 c2 1f bf b5 8d 62 
0b 52 03 03 17 b5 00 00 00 00 45 00 00 3c 40 24 
40 00 38 06 e8 0e 8d 62 0b 52 c2 1f bf b5 90 9a 
01 d1 33 4f a5 db 00 00 00 00 a0 02 72 10 53 ba 
00 00 02 04 05 b4 04 02 08 0a 16 16 e5 ff 00 00 
00 00 01 03 03 07 
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/packet_rs-0.4.0/src/packet.rs:204:36
```

**Comment by zesterer** [comment]
I looks like the implementation of `get_header`/`get_header_mut` are fundamentally broken. I've opened a PR: #3.

**Comment by ravi861** [comment]
Resolved by @zesterer via https://github.com/ravi861/packet-rs/pull/3. Thanks for the contribution.
